services:
  - type: web
    name: my-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: MEDIAPIPE_DISABLE_GPU
        value: 1
      - key: KMP_DUPLICATE_LIB_OK
        value: "True"
      - key: OMP_NUM_THREADS
        value: 4
      - key: MKL_NUM_THREADS
        value: 4
      - key: OPENBLAS_NUM_THREADS
        value: 4
      - key: NUMEXPR_NUM_THREADS
        value: 4
      - key: VECLIB_MAXIMUM_THREADS
        value: 4

